---
services: [docker]
language: python
env:
  global:
    - |
      COPS_POSTGIS_VERSION="2.5" \
      RELEASE_DEBUG="" \
      NBPARALLEL="2" \
      DO_RELEASE="1" \
      RELEASABLE_REPOS="corpusops/" \
      COPS_URL="https://github.com/corpusops/corpusops.bootstrap" \
      COPS_ROOT="$TRAVIS_BUILD_DIR/local/corpusops.bootstrap" \
      funcs="$COPS_ROOT/bin/cops_shell_common" \
      silent="$funcs output_in_error silent_vv" \
      apply_role="sudo -E $silent $COPS_ROOT/bin/cops_apply_role -vvvvv" \
      install="sudo -E $silent $COPS_ROOT/bin/install.sh" \
      sync_code="$install -C --synchronize-code --skip-sync-core" \
      release="$COPS_ROOT/hacking/docker_release" \
      silent_rm="$silent rm -rf"
  matrix:
  - IMAGES="corpusops/postgis-bare/11-2.5 corpusops/postgis-bare/10-2.4 corpusops/postgis-bare/10-2.5 corpusops/postgis-bare/9.0-2.1 corpusops/postgis-bare/9.1-2.2 corpusops/postgis-bare/9.2-2.2 corpusops/postgis-bare/9.2-2.3 corpusops/postgis-bare/9.3-2.3 corpusops/postgis-bare/9.3-2.4 corpusops/postgis-bare/9.4-2.3 corpusops/postgis-bare/9.4-2.5 corpusops/postgis-bare/9.5-2.4 corpusops/postgis-bare/9.5-2.5 corpusops/postgis-bare/9.6-2.4 corpusops/postgis-bare/9.6-2.5 corpusops/postgis-bare/9.4-2.4"
  - IMAGES="corpusops/postgis-bare/11-2.5-alpine corpusops/postgis-bare/10-2.4-alpine corpusops/postgis-bare/10-2.5-alpine corpusops/postgis-bare/9.2-2.3-alpine corpusops/postgis-bare/9.3-2.3-alpine corpusops/postgis-bare/9.3-2.4-alpine corpusops/postgis-bare/9.4-2.4-alpine corpusops/postgis-bare/9.4-2.5-alpine corpusops/postgis-bare/9.5-2.4-alpine corpusops/postgis-bare/9.5-2.5-alpine corpusops/postgis-bare/9.6-2.4-alpine corpusops/postgis-bare/9.6-2.5-alpine"
# all images that werent explicitly told to be built would be built in the next batches
# we span them onto N jobs
cache: {directories: ["$HOME/.cache/pip", "$COPS_ROOT"]}
before_install:
# will fail when upper image will support a new postgis version => and we will have to manually
# # fix the ci pipeline with what will be on upstream
- "curl -f https://raw.githubusercontent.com/appropriate/docker-postgis/master/11-$COPS_POSTGIS_VERSION/Dockerfile >/dev/null"
- sudo apt-get update -qq
- sudo apt-get install -qq -y --force-yes parallel
- sudo service docker stop
- ./main.sh refresh_corpusops
- sh -c "$apply_role */*/roles/corpusops.roles/services_virt_docker/role.yml"
- i=$(whoami) && sudo chown -Rf $i $COPS_ROOT
script:
- echo "building $IMAGES" >&2
# for any released tags from where we did our last maintenance, get a chance to discover and build it
- cd "$TRAVIS_BUILD_DIR" && $silent ./refresh_images.sh
- cd "$TRAVIS_BUILD_DIR" && export DO_RELEASE=1 && $silent ./build.sh $IMAGES
